version: 2
updates:
- package-ecosystem: "cargo"
  directory: "/"
  schedule:
    interval: "weekly"
  ignore:
  - dependency-name: "sycamore"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
