[package]
name = "wasme"
description = "About Me in Rusty WASM"
repository = "https://github.com/aquarhead/wasme"
license = "CC-BY-NC-4.0"
version = "0.2.0"
authors = ["LOU Xun <aquarhead@ela.build>"]
edition = "2021"

[dependencies]
sycamore = { git = "https://github.com/sycamore-rs/sycamore" }
