[tasks.compile_release]
command = "cargo"
args = ["build", "--release"]

[tasks.create_wasm_release]
description = "Build with wasm-pack"
install_crate = { crate_name="wasm-pack", binary="wasm-pack", test_arg="-V", min_version="0.8.0" }
command = "wasm-pack"
args = ["build", "--target", "web", "--out-name", "package"]

[tasks.release]
description = "Build, and create wasms, with the release flag"
workspace = false
dependencies = ["compile_release", "create_wasm_release"]

[tasks.serve]
description = "Start server"
install_crate = { crate_name="microserver", binary="microserver", test_arg="-h" }
workspace = false
command = "microserver"
args = ["--port", "8000"]

[tasks.start]
description = "Combine the build and serve tasks"
workspace = false
dependencies = ["release", "serve"]
