name: Build and Deploy
on:
  push:
    branches: [master]
jobs:
  build-n-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache build
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('Cargo.lock') }}
      - name: Install cargo-make
        run: |
          wget https://github.com/sagiegurari/cargo-make/releases/download/0.34.0/cargo-make-v0.34.0-x86_64-unknown-linux-musl.zip
          unzip cargo-make-v0.34.0-x86_64-unknown-linux-musl.zip
          mv cargo-make-v0.34.0-x86_64-unknown-linux-musl/cargo-make ~/.cargo/bin/
      - name: Build
        run: cargo make release
      - name: Collect artifacts
        if: success()
        run: |
          mkdir -p artifact/pkg
          mv index.html artifact/index.html
          mv assets artifact/assets
          mv pkg/package.js artifact/pkg/package.js
          mv pkg/package_bg.wasm artifact/pkg/package_bg.wasm
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: wasme
          path: artifact
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./artifact
          cname: aqd.is
