name: Build and Deploy
on:
  push:
    branches: [master]
jobs:
  build-n-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo bin
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cargo-make
        run: cargo install cargo-make
      - name: Build
        run: cargo make build_release
      - name: Collect artifacts
        if: success()
        run: |
          mkdir -p artifact/pkg
          mv index.html artifact/index.html
          mv assets artifact/assets
          mv pkg/package.js artifact/pkg/package.js
          mv pkg/package_bg.wasm artifact/pkg/package_bg.wasm
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: wasme
          path: artifact
      - name: Deploy
        if: success()
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mv artifact ~/wasme
          mkdir ~/.ssh
          echo $DEPLOY_KEY > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo ${{ secrets.SERVER_FINGERPRINT }} >> ~/.ssh/known_hosts
          chmod +x ~/wasme
          echo ${{ secrets.DEPLOY_CMD }} >> ./sync.sh
          chmod +x ./sync.sh
          ./sync.sh
